# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AutoDriveOutput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAutoDriveOutput(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AutoDriveOutput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def AutoDriveOutputBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x56\x50\x4F\x31", size_prefixed=size_prefixed)

    # AutoDriveOutput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AutoDriveOutput
    def DistNormalized(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AutoDriveOutput
    def CurvatureRaw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AutoDriveOutput
    def FlagProb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AutoDriveOutput
    def Valid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def AutoDriveOutputStart(builder): builder.StartObject(4)
def AutoDriveOutputAddDistNormalized(builder, distNormalized): builder.PrependFloat32Slot(0, distNormalized, 0.0)
def AutoDriveOutputAddCurvatureRaw(builder, curvatureRaw): builder.PrependFloat32Slot(1, curvatureRaw, 0.0)
def AutoDriveOutputAddFlagProb(builder, flagProb): builder.PrependFloat32Slot(2, flagProb, 0.0)
def AutoDriveOutputAddValid(builder, valid): builder.PrependBoolSlot(3, valid, 0)
def AutoDriveOutputEnd(builder): return builder.EndObject()
