# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AutoSpeedOutput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAutoSpeedOutput(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AutoSpeedOutput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def AutoSpeedOutputBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x56\x50\x4F\x31", size_prefixed=size_prefixed)

    # AutoSpeedOutput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AutoSpeedOutput
    def Detections(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from visionpilot.wire.Detection import Detection
            obj = Detection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AutoSpeedOutput
    def DetectionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AutoSpeedOutput
    def DetectionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # AutoSpeedOutput
    def Valid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def AutoSpeedOutputStart(builder): builder.StartObject(2)
def AutoSpeedOutputAddDetections(builder, detections): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(detections), 0)
def AutoSpeedOutputStartDetectionsVector(builder, numElems): return builder.StartVector(24, numElems, 4)
def AutoSpeedOutputAddValid(builder, valid): builder.PrependBoolSlot(1, valid, 0)
def AutoSpeedOutputEnd(builder): return builder.EndObject()
