# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CIPOFusionEstimate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCIPOFusionEstimate(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CIPOFusionEstimate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def CIPOFusionEstimateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x56\x50\x4F\x31", size_prefixed=size_prefixed)

    # CIPOFusionEstimate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CIPOFusionEstimate
    def Valid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CIPOFusionEstimate
    def DistanceM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CIPOFusionEstimate
    def VelocityMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CIPOFusionEstimate
    def DistanceStddevM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CIPOFusionEstimate
    def CipoRawFound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CIPOFusionEstimate
    def CipoRawDistM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CIPOFusionEstimate
    def CutInDetected(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def CIPOFusionEstimateStart(builder): builder.StartObject(7)
def CIPOFusionEstimateAddValid(builder, valid): builder.PrependBoolSlot(0, valid, 0)
def CIPOFusionEstimateAddDistanceM(builder, distanceM): builder.PrependFloat32Slot(1, distanceM, 0.0)
def CIPOFusionEstimateAddVelocityMs(builder, velocityMs): builder.PrependFloat32Slot(2, velocityMs, 0.0)
def CIPOFusionEstimateAddDistanceStddevM(builder, distanceStddevM): builder.PrependFloat32Slot(3, distanceStddevM, 0.0)
def CIPOFusionEstimateAddCipoRawFound(builder, cipoRawFound): builder.PrependBoolSlot(4, cipoRawFound, 0)
def CIPOFusionEstimateAddCipoRawDistM(builder, cipoRawDistM): builder.PrependFloat32Slot(5, cipoRawDistM, 0.0)
def CIPOFusionEstimateAddCutInDetected(builder, cutInDetected): builder.PrependBoolSlot(6, cutInDetected, 0)
def CIPOFusionEstimateEnd(builder): return builder.EndObject()
