# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Detection(object):
    __slots__ = ['_tab']

    # Detection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Detection
    def X1(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Detection
    def Y1(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Detection
    def X2(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Detection
    def Y2(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # Detection
    def Score(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # Detection
    def ClassId(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))

def CreateDetection(builder, x1, y1, x2, y2, score, classId):
    builder.Prep(4, 24)
    builder.PrependInt32(classId)
    builder.PrependFloat32(score)
    builder.PrependFloat32(y2)
    builder.PrependFloat32(x2)
    builder.PrependFloat32(y1)
    builder.PrependFloat32(x1)
    return builder.Offset()
