# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InferenceFrameResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInferenceFrameResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InferenceFrameResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def InferenceFrameResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x56\x50\x4F\x31", size_prefixed=size_prefixed)

    # InferenceFrameResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InferenceFrameResult
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InferenceFrameResult
    def TotalMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # InferenceFrameResult
    def PreMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # InferenceFrameResult
    def VisionpilotMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # InferenceFrameResult
    def AutoDrive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from visionpilot.wire.AutoDriveOutput import AutoDriveOutput
            obj = AutoDriveOutput()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InferenceFrameResult
    def AutoSteer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from visionpilot.wire.AutoSteerOutput import AutoSteerOutput
            obj = AutoSteerOutput()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InferenceFrameResult
    def AutoSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from visionpilot.wire.AutoSpeedOutput import AutoSpeedOutput
            obj = AutoSpeedOutput()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InferenceFrameResult
    def Cipo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from visionpilot.wire.CIPOFusionEstimate import CIPOFusionEstimate
            obj = CIPOFusionEstimate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InferenceFrameResult
    def Lateral(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from visionpilot.wire.LateralFusionEstimate import LateralFusionEstimate
            obj = LateralFusionEstimate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def InferenceFrameResultStart(builder): builder.StartObject(9)
def InferenceFrameResultAddFrameId(builder, frameId): builder.PrependUint64Slot(0, frameId, 0)
def InferenceFrameResultAddTotalMs(builder, totalMs): builder.PrependFloat64Slot(1, totalMs, 0.0)
def InferenceFrameResultAddPreMs(builder, preMs): builder.PrependFloat64Slot(2, preMs, 0.0)
def InferenceFrameResultAddVisionpilotMs(builder, visionpilotMs): builder.PrependFloat64Slot(3, visionpilotMs, 0.0)
def InferenceFrameResultAddAutoDrive(builder, autoDrive): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(autoDrive), 0)
def InferenceFrameResultAddAutoSteer(builder, autoSteer): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(autoSteer), 0)
def InferenceFrameResultAddAutoSpeed(builder, autoSpeed): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(autoSpeed), 0)
def InferenceFrameResultAddCipo(builder, cipo): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(cipo), 0)
def InferenceFrameResultAddLateral(builder, lateral): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(lateral), 0)
def InferenceFrameResultEnd(builder): return builder.EndObject()
