# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LateralFusionEstimate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLateralFusionEstimate(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LateralFusionEstimate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def LateralFusionEstimateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x56\x50\x4F\x31", size_prefixed=size_prefixed)

    # LateralFusionEstimate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LateralFusionEstimate
    def Valid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # LateralFusionEstimate
    def CteM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def CteRateMps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def YawRad(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def YawRateRps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def CteStddevM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def YawStddevRad(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def Curvature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def CurvStddev(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def PathValid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # LateralFusionEstimate
    def RawCteM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def RawYawRad(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def RawPathCurvature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def RawAdCurvature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def PathInliers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LateralFusionEstimate
    def PathPoints(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LateralFusionEstimate
    def PathA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def PathB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def PathC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def PathXMinM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LateralFusionEstimate
    def PathXMaxM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def LateralFusionEstimateStart(builder): builder.StartObject(21)
def LateralFusionEstimateAddValid(builder, valid): builder.PrependBoolSlot(0, valid, 0)
def LateralFusionEstimateAddCteM(builder, cteM): builder.PrependFloat32Slot(1, cteM, 0.0)
def LateralFusionEstimateAddCteRateMps(builder, cteRateMps): builder.PrependFloat32Slot(2, cteRateMps, 0.0)
def LateralFusionEstimateAddYawRad(builder, yawRad): builder.PrependFloat32Slot(3, yawRad, 0.0)
def LateralFusionEstimateAddYawRateRps(builder, yawRateRps): builder.PrependFloat32Slot(4, yawRateRps, 0.0)
def LateralFusionEstimateAddCteStddevM(builder, cteStddevM): builder.PrependFloat32Slot(5, cteStddevM, 0.0)
def LateralFusionEstimateAddYawStddevRad(builder, yawStddevRad): builder.PrependFloat32Slot(6, yawStddevRad, 0.0)
def LateralFusionEstimateAddCurvature(builder, curvature): builder.PrependFloat32Slot(7, curvature, 0.0)
def LateralFusionEstimateAddCurvStddev(builder, curvStddev): builder.PrependFloat32Slot(8, curvStddev, 0.0)
def LateralFusionEstimateAddPathValid(builder, pathValid): builder.PrependBoolSlot(9, pathValid, 0)
def LateralFusionEstimateAddRawCteM(builder, rawCteM): builder.PrependFloat32Slot(10, rawCteM, 0.0)
def LateralFusionEstimateAddRawYawRad(builder, rawYawRad): builder.PrependFloat32Slot(11, rawYawRad, 0.0)
def LateralFusionEstimateAddRawPathCurvature(builder, rawPathCurvature): builder.PrependFloat32Slot(12, rawPathCurvature, 0.0)
def LateralFusionEstimateAddRawAdCurvature(builder, rawAdCurvature): builder.PrependFloat32Slot(13, rawAdCurvature, 0.0)
def LateralFusionEstimateAddPathInliers(builder, pathInliers): builder.PrependInt32Slot(14, pathInliers, 0)
def LateralFusionEstimateAddPathPoints(builder, pathPoints): builder.PrependInt32Slot(15, pathPoints, 0)
def LateralFusionEstimateAddPathA(builder, pathA): builder.PrependFloat32Slot(16, pathA, 0.0)
def LateralFusionEstimateAddPathB(builder, pathB): builder.PrependFloat32Slot(17, pathB, 0.0)
def LateralFusionEstimateAddPathC(builder, pathC): builder.PrependFloat32Slot(18, pathC, 0.0)
def LateralFusionEstimateAddPathXMinM(builder, pathXMinM): builder.PrependFloat32Slot(19, pathXMinM, 0.0)
def LateralFusionEstimateAddPathXMaxM(builder, pathXMaxM): builder.PrependFloat32Slot(20, pathXMaxM, 0.0)
def LateralFusionEstimateEnd(builder): return builder.EndObject()
