# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VisionPilotOutput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVisionPilotOutput(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VisionPilotOutput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def VisionPilotOutputBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x56\x50\x4F\x31", size_prefixed=size_prefixed)

    # VisionPilotOutput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VisionPilotOutput
    def Inference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from visionpilot.wire.InferenceFrameResult import InferenceFrameResult
            obj = InferenceFrameResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VisionPilotOutput
    def Plan(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from visionpilot.wire.Plan import Plan
            obj = Plan()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VisionPilotOutputStart(builder): builder.StartObject(2)
def VisionPilotOutputAddInference(builder, inference): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(inference), 0)
def VisionPilotOutputAddPlan(builder, plan): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(plan), 0)
def VisionPilotOutputEnd(builder): return builder.EndObject()
