# VisionPilot test configuration

source.video_realtime      = true
source.video_loop          = false

source.input_video         = share/tests/test_open_lane_9/input.mp4
source.input_vehicle_speed = share/tests/test_open_lane_9/frame_speed.txt

# zod, open_lane
source.dataset             = open_lane