# VisionPilot configuration template
#   cp config/vision_pilot.conf.example config/vision_pilot.conf

# ─── Input source ────────────────────────────────────────────────────────────
source.mode             = video

source.v4l2_device      = /dev/video0
source.v4l2_fps         = 10

# ─── Inference configs ────────────────────────────────────────────────────────
# Model precision fp32 or int8 for quantized models lowercase
model.precision    = int8
model.auto_drive_model_path = VisionPilot/modules/models/weights/autodrive_core0/autodrive_int8.msgpack
model.auto_steer_model_path = VisionPilot/modules/models/weights/autosteer_core0/autosteer_int8.msgpack
model.auto_speed_model_path = VisionPilot/modules/models/weights/autospeed_core0/autospeed_int8.msgpack

# ───────────────────────────────────────────────────────────────────────────────
speed_limit      = 33.3;   # m/s
Lf               = 2.67    # Front axle to CoG (m). Wheelbase L = Lf + Lr

# ─── GUI ───────────────────────────────────────────────────────────────────────
# Enable/Disable visualization
visualization_on = true

# Enable/Disable webrtc
webrtc_on = false
webrtc_port = 8080