# VisionPilot test configuration

source.video_realtime      = true
source.video_loop          = false

source.input_video         = /home/sergey/DEV/AI/vision_pilot/downloads/test_open_lane_2/input.mp4
source.input_vehicle_speed = /home/sergey/DEV/AI/vision_pilot/downloads/test_open_lane_2/frame_speed.txt
# zod, open_lane
source.dataset             = open_lane